<a href="https://colab.research.google.com/github/shishaq/docs/blob/main/Colab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd

df_unbranded = pd.read_excel('/content/drive/My Drive/WIP Analysis/Kyle_Unbranded Search by Week - by page.xlsx')
df_unbranded.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sum of Clicks,Column Labels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Row Labels,2024-06-09 00:00:00,2024-06-16 00:00:00,2024-06-23 00:00:00,2024-06-30 00:00:00,2024-07-07 00:00:00,2024-07-14 00:00:00,2024-07-21 00:00:00,2024-07-28 00:00:00,2024-08-04 00:00:00,(blank),NaN,Change since July 14th,% of Chng,NaN,NaN,NaN,NaN,NaN
3,GBP Clicks,237,222,287,230,249,241,183,126,114,NaN,NaN,-127,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.codapet.com/cities/nashville-tn?ut...,18,18,24,26,22,19,23,20,13,NaN,NaN,-6,0.047244,NaN,NaN,NaN,NaN,NaN